# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l13Xe0DuxS7fxVegNmV2HlI9zaDQPRUo
"""

!pip install -Uq \
  "numpy==1.26.4" \
  "requests==2.32.3" \
  "neo4j==5.21.0" \
  "langchain==0.2.10" \
  "langchain-core==0.2.23" \
  "langchain-community==0.2.10" \
  "langchain-experimental==0.0.62" \
  "langchain-text-splitters==0.2.4" \
  "langgraph==0.1.8" \
  "langchain-groq==0.1.3"

import os, signal
os.kill(os.getpid(), signal.SIGKILL)



!pip install -Uq langchain-groq==0.1.4

import os, signal
os.kill(os.getpid(), signal.SIGKILL)

import os

# Use neo4j+s for Aura / encrypted, or bolt/neo4j for local if applicable
os.environ["NEO4J_URI"] = "URI"
os.environ["NEO4J_USERNAME"] = "neo4j"
os.environ["NEO4J_PASSWORD"] = "password"

## Graphdb Configuration
NEO4J_URI="URI"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="password"

from langchain_community.graphs import Neo4jGraph
import os

graph = Neo4jGraph(
    url=os.environ["NEO4J_URI"],
    username=os.environ["NEO4J_USERNAME"],
    password=os.environ["NEO4J_PASSWORD"],
)

graph.query("RETURN 1 AS ok")

groq_api_key="groq_api_key"

from langchain_groq import ChatGroq

llm=ChatGroq(groq_api_key=groq_api_key, model_name="llama-3.1-8b-instant")
llm

from langchain_core.documents import Document
text="""
Elon Reeve Musk (born June 28, 1971) is a businessman and investor known for his key roles in space
company SpaceX and automotive company Tesla, Inc. Other involvements include ownership of X Corp.,
formerly Twitter, and his role in the founding of The Boring Company, xAI, Neuralink and OpenAI.
He is one of the wealthiest people in the world; as of July 2024, Forbes estimates his net worth to be
US$221 billion.Musk was born in Pretoria to Maye and engineer Errol Musk, and briefly attended
the University of Pretoria before immigrating to Canada at age 18, acquiring citizenship through
his Canadian-born mother. Two years later, he matriculated at Queen's University at Kingston in Canada.
Musk later transferred to the University of Pennsylvania and received bachelor's degrees in economics
and physics. He moved to California in 1995 to attend Stanford University, but dropped out after
two days and, with his brother Kimbal, co-founded online city guide software company Zip2."""


documents=[Document(page_content=text)]
documents

from langchain_experimental.graph_transformers import LLMGraphTransformer
llm_transformer=LLMGraphTransformer (llm=llm)

graph_documents=llm_transformer.convert_to_graph_documents(documents)

graph_documents

graph_documents[0].nodes

graph_documents[0].relationships

movie_query="""
LOAD CSV WITH HEADERS FROM
'https://raw.githubusercontent.com/tomasonjo/blog-datasets/main/movies/movies_small.csv' as row

MERGE (m:Movie{id: row. movieId} )
SET m.released = date(row.released),
m.title = row. title,
m.imdbRating = toFloat(row.imdbRating)
FOREACH (director in split(row.director, '|') |
MERGE (p:Person {name:trim(director)})
MERGE (p)-[:DIRECTED]->(m))
FOREACH (actor in split(row. actors, '|') |
MERGE (p:Person {name:trim(actor)})
MERGE (p)-[:ACTED_IN]->(m))
FOREACH (genre in split(row.genres, '|') |
MERGE (g:Genre {name:trim(genre)})
MERGE (m)-[:IN_GENRE]->(g))"""

graph.query(movie_query)

from langchain. chains import GraphCypherQAChain
chain=GraphCypherQAChain.from_llm(llm=llm,graph=graph,verbose=True)
chain

response=chain. invoke({"query":"Who was the director of the moview GoldenEye"})

